### ISSUE TITLE
Download button in the menu section

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#120]
I'm not sure the info with the CRC is relevant. Maybe could we remove it, I don't know? I suggest to put the word 'Download' instead of, I'm pretty sure many users won't find the button to download a menu.
 See an example here:

![download](https://user-images.githubusercontent.com/12120244/114313195-d409a900-9af5-11eb-9437-0eddffdeee36.jpg)

**Comment by MugUK** [comment]
Agree with this one. The CRC is only really useful to us in Cpanel?

**Comment by nguillaumin** [comment]
Ah, well I did wonder about CRC how useful it was... I think if we have the information we should display it, could be useful for archivists to compare checksums with their own dumps? But if it's not useful, then I wonder if it's even useful to have in CPANEL / DB (since the CRC can be re-computed anyway) and so maybe we should remove it altogether?

For the download I would like to keep the icon. I think it should be clear, especially since we've used the same icon in the dump download section for single games, and it's followed by the file size. Also there's a text that says you have to log in to download, so it would be pretty obvious for anyone who would have to log in first:

![image](https://user-images.githubusercontent.com/762512/114434014-cff78d00-9bc2-11eb-8be0-3543dbe316de.png)

I don't mind if we want to change the icon to make it more obvious though? Here are possible alternatives: https://fontawesome.com/icons?p=2&q=download&m=free

**Comment by MugUK** [comment]
1st or 2nd icons on the first row seem the most obvious to me.

**Comment by nguillaumin** [comment]
The first one is the one we currently use.

Since there was no more discussion on this and that the download links are now public, I'll close it. Hopefully with the filesize displayed next to it it's pretty clear it's for downloading.
