### ISSUE TITLE
CPANEL - Better visibility for menus missing scrolltexts / screenshots / dumps

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#121]
I've been adding a few scrolltexts using the new Cpanel and whilst this initial version is good, there's a few suggestions I'd like to add (if they can be coded)

On the original screen (in this example for Analog Bubble Bath), I've just added three of the four scrolltexts.

![AnalogBubbleBath(Example)](https://user-images.githubusercontent.com/17252699/114315708-0fa57280-9af8-11eb-80df-32ef6a408a80.png)

However, the icons that appear above a disk image inside the menu editor, don't show up in the list. 

E.g. something like this:

![New List for Menu Cpanel](https://user-images.githubusercontent.com/17252699/114315822-90fd0500-9af8-11eb-84a2-72e893012b3e.png)

This way I can see, which menus don't have a scrolltext, info or screenshots etc.

E.g. Some of the Adrenalin UK menus have scrolltexts, but not all of them. So I went to the last batch (38+) and did those ones first.

Would this feature be possible?

**Comment by nguillaumin** [comment]
It's a bit tricky, because the list here is a list of menus, not a list of disks. But the scrolltexts are stored at the disk level. For example consider Pompey Pirates menu 13, it has 7 disks, so potentially 7 scrolltexts:

![2](https://user-images.githubusercontent.com/762512/114433555-41830b80-9bc2-11eb-9288-59ef6cc57c7b.png)

So we could not display the little icons as we would need 7 sets of them?

Not opposed to the idea, but I'm not sure how we can make it work...

**Comment by MugUK** [comment]
OK, I will leave it with you in case you can work out a miracle :)

**Comment by nguillaumin** [comment]
I did add info about the disks, one per line, with the disk label at the end. Icons are faded if the information is missing:

![1](https://user-images.githubusercontent.com/762512/116814504-8e228c80-ab59-11eb-99a4-c05d0354552f.png)

It's on the dev site if you want to have a look. It will get deployed next time we deploy the development changes (just waiting on last feedback on the menus search #134 to do so)

**Comment by MugUK** [comment]
Nice one. Will make the job easier. I'll be starting on some more
scrolltexts next week.

**Comment by nguillaumin** [comment]
This is now deployed on prod.
