### ISSUE TITLE
Date of uploaded menu

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#129]
MagikGimp has some requests on Atari-Forum:

https://www.atari-forum.com/viewtopic.php?p=415750#p415750

![atari legend menus 01](https://user-images.githubusercontent.com/12120244/114693671-20cdc980-9d1a-11eb-8e73-88be2e9bd861.jpg)

I'm not sure the information about the size of a disk is relevant, but why not after all.
On the other hand, the date of uploading to the site seems important to me.

I am open to discuss, of course 😉

**Comment by nguillaumin** [comment]
The disk size is already displayed, although you have to be logged in to see it:

![1](https://user-images.githubusercontent.com/762512/114751330-4f1cca80-9d55-11eb-9e05-98c8df00238b.png)

I can change if so that it's always displayed if needed, however on small screens it will wrap because there's not enough space:

![2](https://user-images.githubusercontent.com/762512/114751861-f994ed80-9d55-11eb-8326-4cef94780441.png)

The date, why not, but I'm not sure where since there's not a lot of room left contrary to his opinion :wink: I can put it inside the menu description I guess:

![3](https://user-images.githubusercontent.com/762512/114752910-21d11c00-9d57-11eb-8bfa-0f137e1dc9bc.png)

However the dates for all of them currently will be the date of the import, so not very useful... I also put the user but probably not very useful either?

Let me know what you think.

**Comment by MugUK** [comment]
Does he mean "originally released" rather than "uploaded"?  I can reply to him on the forum if necessary?

**Comment by Brume-AL** [comment]
> 
> 
> Does he mean "originally released" rather than "uploaded"? I can reply to him on the forum if necessary?

He asks for the date of upload. His message is here:
https://www.atari-forum.com/viewtopic.php?p=415750#p415750

**Comment by Brume-AL** [comment]
> 
> 
> The disk size is already displayed, although you have to be logged in to see it:
> 
> ![1](https://user-images.githubusercontent.com/762512/114751330-4f1cca80-9d55-11eb-9e05-98c8df00238b.png)
> 
> I can change if so that it's always displayed if needed, however on small screens it will wrap because there's not enough space:
> 
> ![2](https://user-images.githubusercontent.com/762512/114751861-f994ed80-9d55-11eb-8326-4cef94780441.png)
> 
> The date, why not, but I'm not sure where since there's not a lot of room left contrary to his opinion 😉 I can put it inside the menu description I guess:
> 
> ![3](https://user-images.githubusercontent.com/762512/114752910-21d11c00-9d57-11eb-8bfa-0f137e1dc9bc.png)
> 
> However the dates for all of them currently will be the date of the import, so not very useful... I also put the user but probably not very useful either?
> 
> Let me know what you think.

Thanks Nicolas. Yes, you're right: there's no need to put the size when the visitor isn't logged in.

On the other side, the date of the import is be useful for people who visit the site regulary. They want to dowload latest menus added w/o redownload a full set. I guess a tile (we've already discussed about it) with latest menus uploaded should do the job. Same kind of tile there was on Stonish on the Start page on the left.

Last but non least: I guess we'll have to discuss about this "log in" thing. I remember it was a sensitive subject with other members of AL, but I never liked the fact people has to be registered to download our stuffs. Maybe I should open a new thread?

**Comment by nguillaumin** [comment]
Ok, then:
- Please open a separate issue for the log-in situation
- I will create a separate ticket to implement a "last menus added" tile
- I close this one
