### ISSUE TITLE
Can we search menu contents? 

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#134]
Someone on FB is asking how he can search the menus for utility disks with Hisoft BASIC on it. 

When I search for BASIC, nothing comes back. Tried it with game titles to - it only brings back AL entries in the main database.

Is a Menu Search option coming soon? Of if it's there already, where do I look for it?

**Comment by MugUK** [comment]
OK, so it works for some titles. 

But I'm sure GFA BASIC was included on a few menus, but I can't find any occurrence of it. Maybe it's just my corrupted memory playing tricks!?

**Comment by nguillaumin** [comment]
The search currently only searches for games, it has not changed at all in that regard. It just hits the `game` table. Now we have a new, separate table that contains non-game software. Since they're in a separate table we cannot "mix" the two easily.

We could:
- Update the search page to also search for non-games, but we would have to separate it in the search result page (either view Games result, or Software result), maybe in tabs.
  - Also we don't have a lot of information to display for a software (basically the title, link to DemoZoo if there's one, and list of menus it's part of
  - We would also have to consider the auto-suggest on the main search bar. Probably would need to separate in 2 "sections" for game vs. software
- Alternatively keep the search as-is, but introduce a new search inside the Menus page, at the top above or below the A-Z index. This search would search for all titles that are part of menus (game + software) and would return a list of menus that contains the matching title (So basically the same as the list of menus for a set, but for any menu of any set matching the search
- Something else?

Let me know what you think, @Brume-AL @stgraveyard as well.

**Comment by MugUK** [comment]
I like that even Orion/Replicants can't work the search engine, but Brume has the skillz :)

**Comment by stgraveyard** [comment]
I would go for a new search in the menu section, because adding software to the existing doesn't make sense since the existing is situated in the GAME section.

**Comment by Brume-AL** [comment]
That's a good question 🤔

If we add a new search in the menu section, you can be sure that many people won't see it and they'll still complain they don't find they are looking for with the main search engine available everywhere else on the site. And even if we tell them, they'll argue that the main search bar is only for games. Be ready to receive a lot of complaints.

Maybe your first proposition is the best one, Nico. I know we don't have many information to display about demos, tools, etc. But the database is destined to grow year by year.
About the auto-suggest, maybe could we a symbol before each result (a joystick for games, a monitor or a sprite for demos, a tool for profesionnal programs, etc.).

Let me know what you think.

**Comment by stgraveyard** [comment]
@Brume-AL But what about the fact that the search is situated in the 'games' tab? Or am I going too far?

**Comment by Brume-AL** [comment]
@stgraveyard : What do you mean with 'you are going too far'? Sorry if I wasn't very clear, but i was speaking about the lack of full search in the main bar. Pretty sure this is the one everyone uses most of the time. We have to consider that this bar needs a search engine for all databases (games, demos, tools...).
Of course a seperate search option in the menu section could be added, too. If so, it means that the day we open a 'tools' section, a 'demos' section or a 'source' section, each one will offer its own search option.

**Comment by stgraveyard** [comment]
Ah ok. Sounds perfect Bruno!

**Comment by nguillaumin** [comment]
I have implemented a few things:
- The auto-complete now shows both games and software, with icons to distinguish as per Brume's idea. I used [this icon](https://fontawesome.com/icons/desktop?style=solid) for software, let me know if you have a better idea (Look in the [free icons](https://fontawesome.com/icons?d=gallery&p=2&m=free) from Font Awesome)
- The search results now have a 2 tabs at the top showing the number of Game matches and Software matches
- The Software tab just shows all matching software, with their type and DemoZoo link. Initially I tried to put all the menus the software was on but it was too messy, and clicking on the software title gives the same result
- I also added a search box on the menus index page

It is deployed on the [development site](https://dev.atarilegend.com/), let me know what you think?

Not sure if that was ever discussed, but do we want to catalog software as well as games? Then we could add a few fields in the database as well as screenshots, this way the software search results page would look better. I think it would be useful to have a DB of software as well, but I don't know if that is one of AL's goal or not...

**Comment by Brume-AL** [comment]
I love what you've done, Nico! The icons in the search tool bar are perfect!
Also the search engine in the menu section looks fine.

Yes, you're right: we always wanted to include software in AL db. But that's a huge work and we never found the time to add them, make screenshots, etc. We really need this kind of feature on AL. Also Marcer is working on software, too. I guess it may be a great help.

Do everyone agree or am I getting carried away a little too fast? 🤔

**Comment by Marcer75** [comment]
I have a little request. about game Section.. make it possible to choose how to get the games listed. as I prefer without screenshoots. (faster way for me when hunting dupes or such). Im speaking of official site :)
listing mode that shows :-1: 
Title - Year - Developer - Publisher - Year - "have screenshot" - "have boxscan" - "have download" 
"those within can use small clear pictures" if we got its clear.. if missing any a Red cross over or such?

About Download softwares. only able Originals in .STX (100% Dumps) - RawDumps we should better use an FTP later on for.
PD / Demo Versions etc - .MSA formats (If Possible only the Actuall Game files on the dump!).
Cracked Stuff... Im not sure if AL is ready for all those infos atm. Unless we dupe the Game section and make a new Section called "Modifed Games" (sounds better than Cracked games etc). Where we have all the cracked games. this way we could hopefully use Publisher / Developers (places) for Cracker/Crew infos instead.

What do you guys say?

**Comment by Marcer75** [comment]
Also. I think Bindings would work better with "cracked games" and Menus. as many cracked games on Menus is not cracks by the menu makers

**Comment by nguillaumin** [comment]
Hi Marcer, good to see you here :wink: . Would you mind creating separate GitHub issues for these topics? We try to keep one issue per topic otherwise it's hard to have constructive discussions.
- Search without screenshot: Check out the export mode in the search. If you would like changes to it, please create a separate issue
- Download formats: For me it's fine to have the discussion on Atari-Forum. Once we decide create a GitHub issue for me to implement what was decided. Otherwise if we want to discuss it here, please create a separate issue.
- Bindings: Not sure what you mean by that? Separate issue please :smile: 

Let's keep this issue focused on discussing the implementation of searching for menu contents. Thanks!

**Comment by stgraveyard** [comment]
Hi Nico, 

It is nice, but there feel stuff wrong. 

example I go to the menu section and search for 'Word' (as in st word) :  

![image](https://user-images.githubusercontent.com/4339294/116795046-5d4b4480-aad2-11eb-9891-d288745949ab.png)

results seems nice, when I switch tabs, all stays good : 

![image](https://user-images.githubusercontent.com/4339294/116795070-91bf0080-aad2-11eb-99b3-2a08b3a1f081.png)

When I click on games tab, and I search for publisher '16 blitz' I get this : 

![image](https://user-images.githubusercontent.com/4339294/116795093-b3b88300-aad2-11eb-8c3d-c9ba9a55a573.png)

The software results are not OK.

Or when I go to the game section and I press the 'A' I get following results : 

![image](https://user-images.githubusercontent.com/4339294/116795113-dfd40400-aad2-11eb-95b0-7f7a5cf1d1ea.png)

Software is not OK, it shows all software. When I new press the software tab : 

![image](https://user-images.githubusercontent.com/4339294/116795126-f4180100-aad2-11eb-8f15-e49f15d30de0.png)

Than all games are displayed. 

So it is a very nice start and it looks good, but still buggy I think.

**Comment by stgraveyard** [comment]
I REALLY like this : 

![image](https://user-images.githubusercontent.com/4339294/116795148-1f025500-aad3-11eb-86bf-4c42d9019a79.png)

**Comment by nguillaumin** [comment]
Yeah it's quite difficult to get right because games and software have completely different attributes, plus we also want to show all entries when no title is given, but that's the case when search is only made via a publisher for example (no title given → all software are shown...).

I have made a few changes to make it more consistent, please have another look on dev.

**Comment by stgraveyard** [comment]
Ok I understand the problem, but now it is much much better. 

But look at this behavior Nico : 

![image](https://user-images.githubusercontent.com/4339294/116918912-d4a6e280-ac50-11eb-9bdf-bb7f9a95ecf5.png)

Software is now 0, which is good.

I now go to the software tab and all of a sudden we have ALL games : 

![image](https://user-images.githubusercontent.com/4339294/116919003-f2744780-ac50-11eb-94bb-ab2e98d1e839.png)

This is ofcourse because in software we don't have publisher, so we lose this data. 

So maybe we need to store all data in temp vars in php for the queries? 

We could leave it as is, but still it feel weird when I use it now. It is much much better, but this is still odd.

What do you think?

**Comment by nguillaumin** [comment]
Fair point. I'd rather not use temp vars / session variables as they come with a bunch of drawbacks.

I think the simpler would be to also return 0 results for games when no title has been entered. That would be consistent with the software search, and possibly make more sense rather than returning everything. Only drawback is that there would be no way to view all games, but looking at the analytics nobody seems to use it... If that's a problem we can also add an "ALL"  link in the A-Z index.

**Comment by stgraveyard** [comment]
This sounds good.

**Comment by nguillaumin** [comment]
Ok, change is applied on dev if you want to check it out.

**Comment by MugUK** [comment]
Working well for me searching for GFA stuff.

**Comment by stgraveyard** [comment]
Hi Nico, 

This is it. Thanks! 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks, this is now on prod.
