### ISSUE TITLE
Atari repro boxes

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#140]
Hello all,

Robert Tersci, the creator of the Atari ST box repro's, and a good contact of me, has asked if AL could host his box PDFs using our creative commons disclosure. He had them on GITHUB, but now some store has used them for commercial use without even asking. He wants them usable for everyone, but he at least likes some recognition. 
So I want to host these files on AL. Is there a good place we can add them. I have bought lots of boxes from him (as you can see in my videos) and I want this guy motivated. I was thinking of adding them somewhere in the box where we have the DB for download but that is not correct.

Some ideas or opinions appreciated.

Thanks
Maarten

**Comment by nguillaumin** [comment]
Could we use the Spotlight tile for this? It's a bit like promoting the other Spotlights we have like books? We could also add that tile in a few more pages (it's only on the home now I think).

The files themselves we would probably put on GitHub as well in the end so that they get deployed with the site like the other static resources.

In practice it won't really change his situation where anybody could use the files to sell boxes. He could also just add a CC license on his GitHub repo... Or where you thinking of "protecting" them by requiring people to log in and/or with some sort of "request" process someone would have to approve in CPANEL or similar?

**Comment by stgraveyard** [comment]
No, I wasn't thinking of protecting them. I was just thinking about the licence stuff you added in regards of our DB and other content.

**Comment by nguillaumin** [comment]
Closing this assuming there's nothing further? Happy to re-open and discuss if needed.

**Comment by stgraveyard** [comment]
I will make a spotlight and load it to git.
