### ISSUE TITLE
"Last Updated" errors in Menu Disks (New Control Panel)

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#141]
MSD/POV has helped me to extract the text from BBC Menus 1 - 6 and I've been correcting the text and placing it into the relevant sections.

However, the "Last updated" entry only seems to change when I added the date of release for Menu 4. No changes are recorded for adding a scrolltext?

But on the Menus page on the main site, they appear as the most recent changes?

**Comment by nguillaumin** [comment]
Hi, I think it's a misunderstanding on the DB structure. What you changed is actually the _disk_, not the menu. It shows when you look at the specific disk:

![1](https://user-images.githubusercontent.com/762512/117040055-c10b8280-ad09-11eb-97e2-60a860bddd97.png)

The menu itself did not change.

The structure is:  Menuset → Menu → Disk. This is needed because some menus have multiple disks (for example Pompey Pirates 13). What is shown in the "latest menus" tile on the site are changes on _disks_, that's why they show up.

The menus themselves, they're more of a "container" that is not really exposed on the site.

Hope it helps?
