### ISSUE TITLE
MAIN SITE/CPANEL - BUG - Comments and game

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#152]
Hi Nico,

Hope you are well. 

Had a weird bug. Somebody had submitted a review on may 30th. I pressed the 'move to comment' because it wasn't really a review. When I did I got following  (all on cpanel ): 

![image](https://user-images.githubusercontent.com/4339294/126894358-bc0f17a4-da59-4626-a4a0-8f3a69bcc44d.png)

The review was converted to a comment perfectly as seen now on main site : 

![image](https://user-images.githubusercontent.com/4339294/126894379-1fc63bc8-8f63-457f-8f9a-14ebf3c8268f.png)

However, when I want to view the game I go to following page : 

![image](https://user-images.githubusercontent.com/4339294/126894393-7514ed4d-efd9-4c21-8b3c-85471223c98c.png)

This seems so weird. Other game pages work fine.

Any idea? 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I did not know this function existed to convert a review to a comment! It looks like it's buggy because it added 2 comments in the comments table, and the second one is completely empty (No user_id, comment text or date) and that's what is crashing the page.

I removed the bad comment from the DB for now, to fix the crash. I'll have a look at fixing the feature from the legacy CPANEL.

**Comment by stgraveyard** [comment]
Thank you Nico. Yes, well, for some people, a review is only 2 paragraphs, so to solve it, this function was added .... a looooong time ago :-)

**Comment by nguillaumin** [comment]
Yeah it makes sense it's a useful function.

I think I found the problem, the wrong ID was passed to a function (ID of the newly added comment instead of the game ID). It was working by chance because comment IDs area currently in 1050 range, and we do have game IDs in that range as well. However we do have gaps in the game ID (There's no game 1060 for example) and by bad luck the comment you added via this function used an ID for which there was no game...

In any case a bug which I fixed by passing the correct ID to the function. So it should not happen anymore, hopefully.
