### ISSUE TITLE
CPANEL - BUG - Menudisk changelog

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#154]
Hi Nico,

I think I see a bug? 

![image](https://user-images.githubusercontent.com/4339294/127765368-53e35725-6473-4144-a1b7-54aaa8af1b78.png)

@Brume-AL has update a menu disk, but on the changelog we have no clue as to which one? Or maybe something went wrong? Was this intentional? 

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Not really intentional, but the changelog only displays the "label" of the menu disk. For example for Pompey Pirates 13 B, the label is "B". "13" is the menu number, part of the menu but not the disk. In most cases there are no labels so it's empty.

I have changed it to display the menu set name and menu number so it will be more clear. Same for the menu changelog that was only displaying the number "13", it will display the menu set name too now (i.e. "Pompey Pirates 13").

It's on dev, will be deployed on prod with the other recent changes.

**Comment by stgraveyard** [comment]
I can not checkt his on dev I guess, so we will see in prod.

Thanks.

**Comment by nguillaumin** [comment]
You can by editing a menu disk on dev. Keep in mind that it will only apply for any _future_ change, as we cannot rewrite past changelog entries easily.

This is being deployed on prod now.
