### ISSUE TITLE
Activity Log has wrong info

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#165]
I've just done all of the Sierra On-Line adventures and when I look down the Activity Log, I apparently did them 20 hours earlier?

![ActivityLogTimesOut](https://user-images.githubusercontent.com/17252699/136854061-3d959526-c146-4a9b-89e8-5ff36ca91afd.png)

**Comment by nguillaumin** [comment]
This is due to the fact that the changelog code in the old CPANEL only stores the date of the change, not the time. So all changes seem to happen at midnight... I have changed it, now the time is recorded too so it should work for future changes. Should be deployed on the site in the next few minutes.

**Comment by MugUK** [comment]
OK, thanks for the fix.
