### ISSUE TITLE
Increase height of Game Facts window

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#167]
I've added a link to the CASA solution for "Eee's Lost His Marbles" (https://www.atarilegend.com/games/5036) but when viewing the game page afterwards, there's too much text in the fact for it all to display correctly.

Can you increase the height of the Game Facts window?
!['EE's Lost His Marbles - Atari ST game - Atari Legend - www atarilegend com](https://user-images.githubusercontent.com/17252699/136937248-ecfbe217-a839-4fa4-8442-bbaf2e5ae0f7.png)

**Comment by nguillaumin** [comment]
This is not a height problem, heights are generally not constrained on the site (it will adapt to the content size). The issue here is with the link syntax:

> The full walkthrough can be found at CASA via this link: [url=https://www.solutionarchive.com/file/id%2C495/]

The link needs to have some kind of text or label, it cannot be the URL alone. For example:

> The full walkthrough can be found at CASA via [url=https://www.solutionarchive.com/file/id%2C495/]this link[/url]

I changed it with the above and now it works.

Unfortunately the BBCode syntax used here is not super obvious. I have in mind to change it to something more widespread like Markdown and/or to provide a better editor if I ever get to rewrite these parts of the CPANEL.
