### ISSUE TITLE
Provide more rows for the menu updates history tile

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#173]
A post in the Atari ST & STE Facebook group has requested that the site history section for the Menus area can be scrolled back and not just show the latest 10 or 20 changes.

**Comment by nguillaumin** [comment]
Hi, I'm not a big fan of "infinite scrolling" and I think it would not work well on mobile because this is already inside a tile, which would cause 2 scrollbars probably... I'll have a look, perhaps I will do a "load more" button instead to fetch the next 20 changes or so.

Alternatively we could have a page that shows the database changelog, like we have in the CPANEL, so that all changes would be visible (not only for menus but all changes in the DB). We could also add an RSS feed for people who want to subscribe.

@stgraveyard do you have any thoughts on this?

**Comment by stgraveyard** [comment]
It's a hard one for me. maybe add a 'more' link which leads to a paging history page of the menus as the main tile?

**Comment by MugUK** [comment]
RSS Feed would be a worthwhile addition.

**Comment by nguillaumin** [comment]
I added a new page, it's on dev for review: https://dev.atarilegend.com/changelog . It shows the DB changelog with an option to filter by section / sub-section, and corresponding atom feed. I also added a link to this page at the bottom of the "latest menus" card.

It would be nice to link it from elsewhere but there's not a lot of room left in the main menu...

Let me know what you think...

**Comment by stgraveyard** [comment]
Hi Nico,

Beautiful page. What I would do now is change the latest updates tile back to showing only 5 updates or something, so people see the link a bit better. 

Maarten

**Comment by MugUK** [comment]
Nice update list. When it's live it will need some pimping out to show that this new function is available.

**Comment by nguillaumin** [comment]
Thanks, it's deployed on prod and I reduced the number of items in the "latest menus" tile.

**Comment by nguillaumin** [comment]
Good idea! It's done.
