### ISSUE TITLE
Issue with news section?

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#174]
Hi Nico, was looking on the site and saw this : 

![image](https://user-images.githubusercontent.com/4339294/154580355-fb7c7625-dfe8-4b51-a3ec-505f24108e8d.png)

And overhere :

![image](https://user-images.githubusercontent.com/4339294/154580431-bf561759-5038-444f-be7d-7b8fd6f0a5d9.png)

Did something change in conversion of text or something? I am pretty sure this was not the case originally with these posts?

KR,
Maarten

**Comment by nguillaumin** [comment]
Thanks, yes it changed as I realized there was a security issue and the content needed to be encoded. I did not realize some news text had `<br />` in the database though, instead of `\n`. Probably the old CPANEL was using `<br />` for newlines by mistake. I have fixed it in the database. I checked the other sections (Interviews, Reviews, ...) and they look ok.
