### ISSUE TITLE
Issue with nicknames

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#176]
Hi @nguillaumin @Brume-AL 

I think we have a problem. I'm currently adding a new interview for the person Arnaud Kinderman, who was a member of the demo group Synergy and did the level design of the game Crapman. 
I have created this individual in the DB :  

![image](https://user-images.githubusercontent.com/4339294/159186771-81a779ee-9462-4a44-98e6-5a949b794d07.png)

Problem is that I can't add his nickname. His nick is 'Wingleader' (as also seen at demozoo : https://demozoo.org/sceners/2423/

![image](https://user-images.githubusercontent.com/4339294/159186799-e5dbec77-e721-45c8-90e9-7a79fee6e826.png)

Seems we already have a 'wingleader'. When I check him out I see following ;

https://www.atarilegend.com/admin/games/individuals/2476/edit

Seems he was part of another crew, not the same person. 

I wonder if there is a solution for this, I think our table set up for individuals was a bit more complex if I remember correctly.

Cheers,
Maarten

**Comment by stgraveyard** [comment]
small correction, the individual is called 'ArnOud Kinderman', I made the change in our DB.

**Comment by nguillaumin** [comment]
I put that check in to prevent duplicates, especially since some individuals are registered with their nick rather than main name. This way you could see "wingman" already exists and add the nick (or main name) rather than creating a duplicate.

However I did not think of the case of valid duplicates, i.e. 2 different persons having the same nick.

I guess either I remove the check, or you have to put some differentiator in the nick like `wingman [Synergy]` ?

**Comment by stgraveyard** [comment]
Good idea

**Comment by MugUK** [comment]
As I'm extracting all of the scrolltexts from various menus, I'm finding out a lot of duplicate names. Maybe our collective teenage years were full of the same TV programs, films etc. that there was a limited pool to pick your nickname from?

At least mine is because I couldn't enter 'Mugger Boot' into the hi-score systems of arcade games, hence Mug :)

**Comment by nguillaumin** [comment]
Not sure what to do. I can remove the duplicate check on the nicks to allow entering a nick that already exists as an individual. But then I should also remove the duplicate check on the individual name, since there can be 2 individuals with the same name, especially if we only have their nicks and not their real name.

Any thoughts?

**Comment by stgraveyard** [comment]
Maybe, istead of a block, we can add a warning. If somebody adds an individual that already exists or is almost the same as an existing one, a popup appears with these individuals and the games or menus they are linked with, with the option to cancel or create new individual anyway?

**Comment by nguillaumin** [comment]
Good idea. I implemented something like that where I display a warning if the main name, or one of the nick has a possible duplicate:

![dup1](https://user-images.githubusercontent.com/762512/164985361-fce56b35-8323-4e94-b975-b94f16cf979b.png)
![dup2](https://user-images.githubusercontent.com/762512/164985363-c17db9dc-affe-40f5-b351-88a07ce3346a.png)

Then you can click on the link to go to the duplicate and see their credits.
