### ISSUE TITLE
Merge of two titles - Grand Prix 500 2 and Hot Rubber

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#185]
They are the same game but with different titles. I am going to assume that Microids release was European (French initially) in 1990, and then Hot Rubber was the re-release by Palace Software in 1991. 

[Gran Prix 2 - https://www.atarilegend.com/games/3659)](Gran Prix 2)
&
[Hot Rubber - https://www.atarilegend.com/games/1928](Hot Rubber)

I've entered the alternative names in both entries - but they show up in the Releases side box as "1991 by Palace Software" on Gran Prix 2 and "1990 by Microids" on the Hot Rubber entry.

Screenshots below:
![Merge Error 2 of 2](https://user-images.githubusercontent.com/17252699/184406746-79fd453a-1414-4d71-a9fc-65d9095afc20.png)
![Merge Error 1 of 2](https://user-images.githubusercontent.com/17252699/184406757-9fa3d7de-73b9-4e97-a11e-f80ba2fff42d.png)

I can delete the information and start again so no major loss. However, what's the proper way to indicate that two releases of the same game had 2 x titles and 2 x publishers? I am trying to make it look like The Sentinel / The Sentry entry.

Even when attending Silly Venture in Poland, I'm still doing db fixes :)

**Comment by nguillaumin** [comment]
I think there's basically two ways:
1. Have a single game, maybe the first one released Grand Prix 500 2, and add all the releases with the alternative names. You can also add an AKA at the game level to make the search work (as search works on games, not releases - For example "The Sentry" is not searchable as it's just a release of "The Sentinel")
2. Have 2 game entries, but avoid creating releases for the other versions, i.e. consider them completely separate games.

I think personally I prefer 1., but it's just a convention the team has to decide. One thing that is possibly missing is to add screenshots specific to a release, so that the "Hot Rubber" title screen could be uploaded to the corresponding release. We planned it when we designed the DB for releases but did not implement it yet.

**Comment by MugUK** [comment]
So is this on hold until there are code changes to allow multiple screenshots to be linked to a variant?

**Comment by nguillaumin** [comment]
Yes I'm afraid so. For now we can keep the 2 separate game entries.

That will take a while because I would only implement release screenshots in the new cpanel, but I need to reimplement all the game/release edit screens first...

**Comment by MugUK** [comment]
Should I remove my attempts at the merge as it looks odd. Or will that work when you've got the time to implement the changes?

**Comment by nguillaumin** [comment]
I think it's ok, since we don't have a consistent way to handle these yet, it's not a big deal...
