### ISSUE TITLE
Getting totals of data from the Search

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#206]
Keops has tagged myself and Brume in an FB post querying just how many commercial titles were released for the Atari ST.

Is this possible using our Search engine and get it to filter out all of the budget titles and remove all traces of PD titles too?

**Comment by nguillaumin** [comment]
It's not possible on the website. I looked into how to do it via database queries but it's not easy because the information about the license or budget title is on the release. Thus you could have a game with 1 release "commercial" and one release "non-commercial" in theory...

FYI:
- Releases with no-license set: 10'070 (Keep in mind that include releases on menus)
- Releases "Commercial": 4'108
- Releases "Non-Commercial":  2'771

And:
- Games with at least 1 commercial release: 3'353 (That include budget releases - however usually a game will have the main "commercial" release + a budget one)

So I think the most accurate count we can provide is 3'353.
