### ISSUE TITLE
Layout issue on game page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#207]
Hi Nico,

I did an upload for the game Cybernoid : https://www.atarilegend.com/games/131

When playing with the responsiveness I have noticed an 'issue' has popped up : 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4339294/210380964-8445551e-7737-4f4e-92ba-b1c28d44098d.png">

As you can see, when you make the window small (like cellphone) it stays in 2 columns, but when you scroll down : 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/4339294/210381167-bca5b4cd-f94d-49f5-b30f-89a8b9462421.png">

The rest of the page goes to 1 column (which is correct).

I know these things are a pain in the butt ... 

KR,
Maarten

**Comment by nguillaumin** [comment]
Hi, yes it's expected like that. The left & right columns in desktop view gets collapsed into 2 columns in small view (displayed first) and the central column in desktop view is kept as a single column on mobile view (because putting the screenshots in 2 columns would make them too small).

If you go even smaller then the 2 columns disappear and only a single remain:

![Cybernoid-The-Fighting-Machine-Atari-ST-game-Atari-Legend](https://user-images.githubusercontent.com/762512/210537243-b6b8dbfa-3fa9-4ac9-9c2d-07bc335729d8.png)

This is the best compromise I could find for all resolutions...

**Comment by stgraveyard** [comment]
Ok, sorry, I stand corrected. Thanks.
