### ISSUE TITLE
Aspect ratio of video box on front page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#219]
Hi Nico,

I noticed today that there was something wrong with the aspect ratio of all of my Youtube thumbs, so I changed them. The resolution is 1280 * 720 (16:9). At the front page it now looks like this : 

<img width="544" alt="image" src="https://github.com/atari-legend/atari-legend/assets/4339294/3c0a60f0-0fd4-4c1c-816c-814495170b12">

On the game detail pages it looks ok : 

<img width="465" alt="image" src="https://github.com/atari-legend/atari-legend/assets/4339294/83326ebe-8a6d-41a6-8f3f-10aa15dd0f3d">

Is it possible to correct on frontpage as well?

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Hi,

The difference between the home page and the game page is that on the game page I'm embedding a YouTube player, so for example you can click "play" and you stay on AL while the video is playing. On the home page it's different, it's just the thumbnail and if you click on it you navigate to the video on YouTube. I did it like that because I was concerned that on the home page there would be 3-4 video and embedding 3-4 players in a single page would slow things down.

For the home page thumbnails I am retrieving them from a YouTube feed, and they come with the black bars.

So the only option would be to switch the home page to also use embedded players.

What do you think?

**Comment by stgraveyard** [comment]
Hi Nico, 

Ok, I understand. For me you can close the topic and leave it as is. No problem.

Thanks,
Maarten
