### ISSUE TITLE
Main - Bug - Game Detail - adding goodies

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#46]
Nico, 

I did a test and added a 'goodie' in the cpanel, a photo of my BMW which I will sell next week :-D 
I know see the goodies are also displayed in the boxscan box : 

![image](https://user-images.githubusercontent.com/4339294/98988819-80843680-2528-11eb-9e81-6037a3122871.png)

Also, I got the question from Mike if he could start adding disk scans (so photo's of the fysical disk). We can add this in the cpanel, but are we also planning this in the main site? Which features from the game release detail at CPANEL level do we have on the proto main site now? 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
For the goodies one could argue it's part of the box so part of the box scans? Alternately we could display them in a separate "goodies" tile on the release page? What do you think?

For the scan of media they are not displayed currently but I can add it. It would be great if the team could upload a few real world dumps + scans + goodies in a few releases in prod so that we have good examples to test. Once it's done I can copy to the dev DB and we can see how it looks.

**Comment by stgraveyard** [comment]
Nico, definetely not in the boxscan tile IMO. I think a seperate tile in the release page would be great. 
I will ask the team to add some dumps, scans, goodies ... and keep you posted.

**Comment by nguillaumin** [comment]
Here's what I came up with:

![4](https://user-images.githubusercontent.com/762512/99145102-11aff600-266c-11eb-89ae-1b6ce6eb3b5f.png)

![5](https://user-images.githubusercontent.com/762512/99145104-14aae680-266c-11eb-971d-e4440ddebf2b.png)

(Note that the floppy on Ultima II appears in the Goodies because it's been set like that in the DB)

Let's see how it looks with a bit more real data, and we can adjust.

**Comment by stgraveyard** [comment]
Yes, very good, I do not see the eco disks at the proto site, guess this is on your server. 

This got me thinking. To make it really really shine, we could as the team to only provide scans of the label of the disk. And we can than program perhaps something that his label is placed on a nice image of a floppy. This way, everything would look nice and standard. Now that would be something, right? ;-)

**Comment by nguillaumin** [comment]
Yes Eco was just a test on my PC.

Nice idea about the labels. I had a similar one for box scans were we could render a 3d box if we have the scans for all sides!

Lots of improvement possible but it needs to go live first 😉

**Comment by stgraveyard** [comment]
> Yes Eco was just a test on my PC.
> 
> Nice idea about the labels. I had a similar one for box scans were we could render a 3d box if we have the scans for all sides!
> 
> Lots of improvement possible but it needs to go live first 😉

I would love that. We also need a mass conversion of the box scans as they are way too big right now...

**Comment by nguillaumin** [comment]
Closing this as it's now live. We can revisit once we have a bit more data.
