### ISSUE TITLE
Changelog user table seems weird

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#62]
Hi Nico,

Something seems a bit off on the changelog now. I have  feeling each time a user updates his profile, we now also get a 'deleted user' line? 

![image](https://user-images.githubusercontent.com/4339294/101980617-ec140d80-3c66-11eb-93a6-0837f2443652.png)

Example above, these users are not deleted (luckily). CB has been a member for a few years now and the other 3 are new accounts.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I fixed the issue for new users. It's because when the user create their account, they are not logged in yet, so we don't know what is user id, but we can take the one from the account they just created.

For the other problem for `cb`, I could not reproduce it, when I change my profile the changelog is correct, weird...
