### ISSUE TITLE
Games displayed on the results page

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#71]
On the previous version of the site, after searching for a game or an editor, all games were displayed on the same pages. Correct me if I'm wrong, but the lines appeared line by line.
Now, the games are displayed on different pages like this:
https://www.atarilegend.com/games/search?developer=Lankhor

Let's discuss about this feature. On my side I really prefer the previous display (one page for all results) but well, that's a matter of taste I guess?

**Comment by stgraveyard** [comment]
Hi Bruno,

This had indeed changed and from my understanding this is because we now follow a bit of a standard (the Laravell / bootstrap templates). Correct me if I'm wrong here @nguillaumin . 

I personally don't mind this. I'm already used to it ;) Some things on the new AL look better, others things need some getting used to. It is a small price to pay for following a standard that others can easily get used to should we get new coders on board.

But again, just my opinion...

Good to have you here on github again Bruno. 

Keep those remarks, bugs and opinions coming! ;)

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Yes this is partly because out of the box the new frameworks (Laravel & Bootstrap) provide pagination controls, whereas having everything on one page would take some work. This is assuming you mean having the "infinite scrolling" which loads results as you scroll the page down.

In addition to extra work, infinite scrolling is sometime seen as bad UX because the user has no clue how much more they must scroll to get to the end of it (the scrollbar has no meaning anymore as things keep refreshing). This is how evil companies :wink: like Facebook and Instagram keep you "engaged" because you keep scrolling down and never reach "the end".

So not keen on re-implementing the infinite scrolling. Alternatively we could display everything in one page directly, but with some limit otherwise the page could become very large.

**Comment by Brume-AL** [comment]
That makes sense, OK.
Maybe could we increase the number of results on the same page?

> Alternatively we could display everything in one page directly, but with some limit otherwise the page could become very large.

Do you suggest to increase the number of results? If so, I totally agree. 12 results is not enough ;)

**Comment by nguillaumin** [comment]
Page count has been increased to 48 results / page.

**Comment by Brume-AL** [comment]
Looks perfect to me, thanks Nico!
