### ISSUE TITLE
AKA titles aren't displayed anymore

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#72]
Some alternative titles aren't displayed anymore. For instance, look at this one:
https://www.atarilegend.com/games/4346
Enter into releases > General section.
Scroll down: realease AKA are there, but they aren't displayed on the main page of the game.
Thanks in advance.

**Comment by nguillaumin** [comment]
AKA at the game level are displayed in the game infobox, see for example:

![1](https://user-images.githubusercontent.com/762512/103155297-b27eee80-479e-11eb-924c-c4e38c4793f4.png)

AKA at the release levels I think were not displayed before, because we had no pages for releases. Now they are part of the release description:

![2](https://user-images.githubusercontent.com/762512/103155304-d5110780-479e-11eb-859d-5fd13803ca6c.png)

Is that OK with you?

Having release-level AKA may be overkill, I think we had the discussion as the time we were building the release structure, but we decided to keep it at the time.

**Comment by Brume-AL** [comment]
Ah, that's OK for me. Thanks for the explanation Nico.

On my side, I regularly forget to click in this field (Release/year) to display the information. For me, the year is used to diplay all titles released the same year.
For instance, in the case of Mémorise game, it's not natural to click on Release>1989 to display info about a release. Maybe we could find another way to do, I really don't know?

Something like that:
Release
> Name of the game (year)

Just my 2 cents of course ;)

**Comment by nguillaumin** [comment]
I agree we somewhat haven't found a good way to navigate to releases. If you recall 2 years ago we had [tons](https://github.com/atari-legend/legacy/issues/223) of [discussions](https://github.com/atari-legend/legacy/issues/647) about this. We got stuck though so when I rebuilt the site I tried to take the simplest approach at least to get something out of the door...

Happy to revisit but needs further discussion, perhaps mockups and ideas, in a new GitHub issue.
