### ISSUE TITLE
N/A screenshots

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#74]
When a game has no capture, something is really missing on the search page. 
This gives the impression that an image has not been loaded, looks like there is an error on the page (even if there is not).

Also on the same capture below, would it be possible to line up screenshots on top? L'Anneau de Zengara is shifted compared to B.A.T. & B.A.T. 2. Same goes for C.L.E.I.A. compared to Back to the Golden Age and Carrier Command.

![image](https://user-images.githubusercontent.com/12120244/103155854-8c0f8200-47a3-11eb-98d3-e0d8e891232f.png)

**Comment by nguillaumin** [comment]
Originally missing screenshots did not have a screenshot box at all. It looked like that (disregard the overlapping text it's a problem with my screenshot tool)

![6](https://user-images.githubusercontent.com/762512/103156192-8e271000-47a6-11eb-9047-efa45f22eaf2.png)

However I thought it was not looking nice because we would get game titles all over the place so I added the `n/a` placeholder.

I can revert it if you want, or I would need ideas about a better-looking placeholder. Maybe @stgraveyard has some ideas too.

**Comment by stgraveyard** [comment]
I think adding a large N/A in the middle of the placeholder could do the trick?

**Comment by nguillaumin** [comment]
Unfortunately it's a bit difficult to center things on both axes. Plus on small screen the `n/a` text tends to go "outside" of the box :disappointed: 

I have made a few changes:
- Added a placeholder image for missing screenshots
- Change alignment to be on the top
- Increase to 48 results per page

![1](https://user-images.githubusercontent.com/762512/103170042-7e103e80-4841-11eb-92bc-10eb08d87a02.png)

Have a look on dev.atarilegend.com and let me know what you think?

**Comment by stgraveyard** [comment]
Hi Nico,

Looks good. I I would b e really picky, I think I would prefer the 'No Screenshot' just horizontal, instead of diagonal. But either way, this will do just fine for me.

Thanks,
Maarten

**Comment by nguillaumin** [comment]
I tried horizontal but it did not work well, however I re-did it with the Audiowide font and now I think it looks good:

![3](https://user-images.githubusercontent.com/762512/103171554-80789580-484d-11eb-861d-b19e042501ba.png)

**Comment by nguillaumin** [comment]
Now deployed on production

**Comment by Brume-AL** [comment]
Looks better with the No Screenshot mention. Thank you.

**Comment by Brume-AL** [comment]
Also the alignment is fine! Thanks again!
