### ISSUE TITLE
MAIN SITE - AL TV tile

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#755]
I see the AL TV tile is now on prod, awesome! 

However, there is small bug (created by me). When you click 'ATARI LEGEND TV' title, you go to the AL history page instead of the youtube channel.

**Comment by nguillaumin** [comment]
What URL should it be?

**Comment by stgraveyard** [comment]
Nico, same as the one at 'read more' in that same tile at the bottom....

**Comment by stgraveyard** [comment]
Also, I think something changed in the css. In phone view / 1 tile view the 'more' and 'read more' don't have an empty line below them and are now right above the border of the tile.
Details, I know, but it wasn't like this...

**Comment by nguillaumin** [comment]
I fixed the link on dev.

For the CSS yes, the problem is that the browser is caching the CSS so when we make a change it does not appear immediately. If you clear your cache it should work. I had the same problem on prod when I deployed the changes the AL TV tile did not look good.

I want to address this at some point by having Grunt automatically add a unique identifier to the CSS to bust the cache.
