### ISSUE TITLE
Why you keep .ssh ?

### ISSUE THREAD

**Issue by maraflush** [atari-legend/atari-legend#756]
Hi,

It would be a good idea to delete this directory (public/.ssh) because it doesn't bring anything and moreover you expose information.
Some public services like https://www.shhgit.com/ on the internet, which analyze the strengths and weaknesses of the keys and sometimes attempt factorizations, etc..

**Comment by nguillaumin** [comment]
Hi, this is used by our automated CI/CD process that deploys on the dev + prod servers, so it does bring something. While we could handle it differently, it's quite convenient.

The only threat model I can think of is someone trying to add their key in there. However we would probably catch it during code review, especially since there are very little contributions for now. And not having the file does not prevent this anyway.

Do you see any other specific risks related to this that should prompt us to revisit this?

**Comment by maraflush** [comment]
As I said nothing prevents someone from retrieving the public key to try to factorize the key (this risk is minor but it exists) and probably knows your assets (server, ci/cd IP address). This is interesting for the OSINT.
You are better aware of your uses than I am.

Regards,

**Comment by nguillaumin** [comment]
Thanks. I think the risk is low, compared to the benefits for now. We will revisit if we start getting more contributions.
