### ISSUE TITLE
Links in reviews don't work anymore

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#80]
Hi Nico,

I was wondering, is a conversion process on the reviews (but carefully) still possible for the links used in there. Example, Super Stario land : 

![image](https://user-images.githubusercontent.com/4339294/104087943-82861f80-5263-11eb-81fe-c08f8622336c.png)

The links 'Richard Davey' and 'Top Byte' don't work anymore?

Just wondering.

Thanks,
Maarten

**Comment by nguillaumin** [comment]
I have added a few more BB tags like `[individual=1234]`, `[publisher=1234]`, `[developer=1234]` so that we can replace these links. I have fix all reviews and interviews, except the latest interview which is not published yet. Since you're still working on it, could you do it? Just replace any URL with `games_main_list` by one of the BBTags.

(I have also fixed a bug with the interview edit screen and screenshots missing comments).

I will also update the CPANEL edit screen with the new BBTag buttons.

**Comment by nguillaumin** [comment]
CPANEL has been updated with new BBTag buttons. So we should be good here.
