### ISSUE TITLE
Random Menu tile - Layout

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#83]
Hi Nico,

Absolutely gobsmacked by the whole menu section. Amazing! 

The random menu tile : 

![image](https://user-images.githubusercontent.com/4339294/107877358-36ff0b00-6ecc-11eb-90ee-43be77ab728b.png)

- The DZ icon. Why also not AFTER the actual tilte, and maybe also in grayscale? 
-  When clicking on the title you either go to the software section or the game section - OK 
- When clicking on the 'I' you go to the release of the game. I would definitely change the 'I' to maybe a grayscale 'release' text or something, as the 'I' is used for extra info on other pages of the project. 
- When clicking on the 'I' of laserchase 2000 you go to this page : 
![image](https://user-images.githubusercontent.com/4339294/107877498-28fdba00-6ecd-11eb-99d7-69131b68bc3b.png)
You can say it says 'NO Date' but the releases both have 1993 with them.  When you check the top bar, the release number is '15879', however, the other 2 releases in 1993 (which both seem the same), both have a different release number. This is SO confusing to me. Why is there no menu disk info so we clearly see this is from the menu disk we clicked?
- Powercopy has a version nr, Obsession II had 'STE'. I guess these are software options? I think there should be some kind of distinction between the links (like DZ and 'I') and the options. Maybe place all links in front of the title and all options after. Or all options between brackets, or on a new line. I just think it now is a bit of a mix up.

Checking out more tiles : 

![image](https://user-images.githubusercontent.com/4339294/107879316-6e73b480-6ed8-11eb-988f-d40faa555f7c.png)

This is do like. I understand the usage of the 'I'. I would prefer something else, but I don't know what. 
Some title contain [doc], while others don't. This I understand, but one could argue why the other titles don't have [game] of [software]. But this is nitpicking. I see now that options are between () and types are [], which is nice.

![image](https://user-images.githubusercontent.com/4339294/107879377-bdb9e500-6ed8-11eb-8e34-d977634f332a.png)

Version nrs don't have any () or []

![image](https://user-images.githubusercontent.com/4339294/107879413-e7730c00-6ed8-11eb-9914-d3981b2978e8.png)

Why is there a limit? (I see now this was decided in another thread for the main game page? I agree)

![image](https://user-images.githubusercontent.com/4339294/107879458-25703000-6ed9-11eb-9496-47fdac6be5ca.png)

This is again very confusing to me (but this could be my lack of knowledge). when clicking on the first newzeeland story 'i' we go to the same release as when clicking on the cheat code version? Why is there an 'i' at the cheatcode version? 

![image](https://user-images.githubusercontent.com/4339294/107879539-ad563a00-6ed9-11eb-9961-0bc8eb5aa4e6.png)

When clicking on any 'i', I really think it should say more than just 'this release is unofficial'. It should clearly state this is the release from this menu disk ... OR maybe we can totally remove the 'i' because it just doesn't add up. When we click the 'i' of Carv Up for example, we go to this page : 

![image](https://user-images.githubusercontent.com/4339294/107879618-2fdef980-6eda-11eb-812c-39dc2d819db8.png)

But I wonder why, there is no info, and there will never be a download, as the download is on the menu disk page or the menu tile of the game detail page : 

![image](https://user-images.githubusercontent.com/4339294/107879647-60bf2e80-6eda-11eb-951d-cfd728c41e80.png)

Cheers,
Maarten

**Comment by stgraveyard** [comment]
This is a detail page that I understand : 

![image](https://user-images.githubusercontent.com/4339294/107880783-56546300-6ee1-11eb-9a0d-156110e431f0.png)

But the Nebulous and ROTJ pages are useless, it seems to me...

**Comment by nguillaumin** [comment]
So there's a lot to unpack here, and most of it has to do with the way the data is stored in Stonish, which I tried to preserve:
- Each menu entry can have:
  - A version (e.g. "2.04"). These are displayed in small next to the title
  - Requirements (e.g. "TOS 1.04 only"). These are displayed in braces `(...)`
  - A sub-type (e.g. "doc"). These are displayed in square braces `[...]`

The sub-type is complicated: When it's `[doc]` it means it's a doc for a game, when it's `[cheats]` it's cheat codes for a game, etc. But it can either be:
1. A doc for the game release that's on the same disk (See for example [Adrenalin UK 1](http://www.stonish.net/Adrenalin-UK-3#st5) which has "Oh-No! more Lemmings"  and also the doc for it
2. Or a doc for a game which is not part of the menu, see for example the [Sewer Doc Disks](http://www.stonish.net/Sewer-Doc-Disc-315#st1), which contains only documentation but no actual game

For case 1., it means the doc applies to a specific release, so we can provide a ℹ️ icon with a link to the release. This is the same release that's part of the disk. For case 2. there's no release to link to, it's just a generic doc for a game, so we link to the game page.

So I don't think we should add `[game]` of `[software]` because this is **not** the type of software, it's really a "subtype". On the same menu disk you can have the game, and the doc for it. If we were to add `[game]` then almost every single menu entry would have `[game]` which would be very noisy.

Regarding the limit in the number of items to show, I think it's necessary because some menus have dozens of entries (See for example [Sewer Doc Disk 1](https://menus.atarilegend.com/menusets/186) )

I hope that clarifies a bit? What I can try is:
- Greyscale the DZ icon, good idea, and move it after the title
- Maybe move the version number to be part of the title (e.g [ProCopy 2.04]()) rather than being small after the title
- Remove the ℹ️ icon for sub-types like `[doc]`, `[cheats]`, etc. It's not very useful and it's confusing
- Update the release page to show that it's on a menu. You're right this is necessary, I overlooked it. Also display other releases that are part of other menus, in the list of releases

**Comment by nguillaumin** [comment]
I have done the above, except updating the release page.

**Comment by stgraveyard** [comment]
Nico, Thank you for the clarification and for keeping up with my ramblings. I'm just trying to depict my confusion (and lack of knowledge) of these parts of the menus. 

_Greyscale the DZ icon, good idea, and move it after the title_ --> This did not happen but it is ok for me
_Maybe move the version number to be part of the title (e.g ProCopy 2.04) rather than being small after the title_ --> Look much better to me now
_Remove the ℹ️ icon for sub-types like [doc], [cheats], etc. It's not very useful and it's confusing_ --> Well done

_Update the release page to show that it's on a menu. You're right this is necessary, I overlooked it. Also display other releases that are part of other menus, in the list of releases_ 
For my understanding, let's check this. As an example we have Reanimators 18 : 

![image](https://user-images.githubusercontent.com/4339294/107987309-0dc6a380-6fce-11eb-9169-fde3074641ca.png)

Let's click on 'i' of the game strider II : 

![image](https://user-images.githubusercontent.com/4339294/107987411-3e0e4200-6fce-11eb-9b1c-01119b0aabea.png)

Now we have no clue where we ended up. On the left we see the game title, this is ok. Boxscan? I don't know, a bit confusing as we are dealing with a menu release. Releases time, again, I'm not sure. But ofcourse, I understand this is the way the site is structured, I just want to make it more obvious we are still in the menu section. 
However, we can make it much better for example by replacing the 'media and downloads' tile with a complete tile of reanimators 18 (like in the menu search results) but with the strider II title highlighted : 

![image](https://user-images.githubusercontent.com/4339294/107987652-b1b04f00-6fce-11eb-8135-2ff5b3c59113.png)

Below this tile, we can also add the multiple tiles of 'strider II can be found on following menu disks' as in the game detail page : 

![image](https://user-images.githubusercontent.com/4339294/107987732-dad0df80-6fce-11eb-9817-02a5b3f2baf6.png)

Now, lets go back to reanimators 18 tile and click a software, pfx packer :

![image](https://user-images.githubusercontent.com/4339294/107987872-1f5c7b00-6fcf-11eb-8d32-a2d63cbf9758.png)

We enter this page, not a release page, but more a menu search result page with a comment. Honestly, I like this nico. Maybe we could use this layout also for the release page of menu games (when clicking the 'i'). 
I wonder why we go to different pages when clicking a game or a software? They are from the same menu. You understand my confusion?

Now finally, let's see where we go when we click on the demo :-) 

![image](https://user-images.githubusercontent.com/4339294/107988030-73675f80-6fcf-11eb-9b8a-46bfd64e66d6.png)

Again, on what looks more like the search result page with some nice info. 

Is it just me or does this part need a bit more 'visual' structure?

Cheers.

**Comment by nguillaumin** [comment]
I have tweaked the release page for menus a bit. I have added the menu it's part of in the description, and also added the corresponding menu tile on the right. I have removed Boxscans and Media & Download which did not make sense. I have added a download link on the menu tile. Problem now though is that the middle column is mostly empty.

I tried to list all other menus for the game, but I think it's even more confusing. It was making the release page look exactly like the game page, with menu tiles at the bottom. Plus it does not really make sense since this *specific release* is only present on a single menu (since it's the release of the menu).

I agree it's a bit confusing, but I'm not sure what the solution is. We basically have 3 type of links:
1. Link to a game: We link to the game page, that lists all other menus this game is part of
2. Link to a software: We link to the software page, that lists all other menus this software is part of
3. Link to a specific release of a game, for this menu only (to document trainers, etc.). Here we show which menu it's part of, but it doesn't really make sense to show other menus

1 and 2 provide the same feature. In both cases it's the page for an "entity" (game or software), listing other menus it's also present on. The software page looks more like search results, beacuse we don't have any other information about the software (since we don't store any details in the DB). If we had we would show screenshots, comments, reviews... and it would look more like the game page.

Have a look at the updated release page and let me know what you think, or if you have other ideas...

**Comment by stgraveyard** [comment]
Thanks Nico, I really appreciate all your efforts. 

I agree with you, we are not there yet, but I understand now we need a 'release' page as well. But I still think the release page should have the same 'look' as the software page, because in essence, this release page is only created for extra info on this specific release (of which we currently have very little to none in the database). So let's check again with screenshots. 

This is the release page now (and let's take reanimators 18 again) : 

![image](https://user-images.githubusercontent.com/4339294/108640500-4d8ffe00-749a-11eb-90cf-92fba7ab2e8a.png)

So in the middle we have the release info from this menu disk. Left we have a screenshot of the game. Submit info should be removed. And the other releases as well, no? Isn't that confusing? Right we have the menudisk. 

Now let's compare to a software : 

![image](https://user-images.githubusercontent.com/4339294/108640573-cf802700-749a-11eb-95fe-2db730e6d02e.png)

Wouldn't it be better if we take the best of these 2 pages. 
So how about this. Left we have the screenshot. Below that the indepth reviews. In the middle we have the menudisk info box (like we have now). Below we have the menu disk content (so like you see in the software page), instead of the small tile on the right. _And below this, we have 'This game is also found in the following menus' OR 'Some other releases by Reanimators' and we show 5 random releases._ (--> This is not a must, once you have the detail of the menu in the middle, I think the open space issue is already almost gone.)  And on the left we have the latest comments tile.

This way we have the same look as the other links. Or am I making matters even worse now?

**Comment by nguillaumin** [comment]
I think I disagree with most of it :laughing: Man this is tough...
- Submit info could be kept, because someone may want to submit info for that specific release (e.g. "Blood Money on this menu has a trainer for infinite lives")
- Menudisk infobox: I don't think would look good inthe center column
- "Game also found on the following menu": Does not make sense to me as we're on the release page. If you want to see this, you should go to the game page
- Display other random menus for the same group: Not a bad idea :wink: 

I tried to take a step back, and I realized maybe we should not have a page for these releases, because we are failing to find a good way to build it, plus we actually don't have a lot of info to show.

So I tried something else: Just display the release-specific info (trainer, language, incompatibilities...) in a little popup when ℹ️ is clicked. It re-uses the same textual description approach as on the release page. Here's an example with some fake data I put in:

![1](https://user-images.githubusercontent.com/762512/109387392-86e4c580-7901-11eb-98ba-77432b2bef04.png)

With this releases are still in the database and can be edited in CPANEL to change trainer options, etc. But we don't have a specific page for it, we just display the info like this. In practice no menu release currently have any info (since the Stonish DB did not have info about trainers, etc.) there will be no ℹ️ displayed. But as release info gets added via CPANEL, they will start to appear.

Unfortunately you can't test by yourself as there's no CPANEL on the test menu site. I hope the screenshot is enough to see how it would look.

Let me know what you think?

**Comment by stgraveyard** [comment]
Nico, I like this very much indeed! 
Only remark I have, is maybe use an enter after every subject. So for example : 
Following languages : French, dutch
[enter] It supports following resolutions : med, high
[enter] ... 
Just to make the text more visible in the box. 

But I REALLY like this idea! This way, it is not confusing anymore for me.

**Comment by nguillaumin** [comment]
Thanks. I wanted a new line as well but I thought the Bootstrap popover component did not allow this. I found a way now, it looks like this:

![2](https://user-images.githubusercontent.com/762512/109393340-59a80f80-7921-11eb-9863-0a6e88456ca8.png)

**Comment by stgraveyard** [comment]
Nico, one more thing. Can you put the DB entries in bold? Like 'French', 'Enhanced for STe', 'Memory' ... Could make it look even better. Also, why is there no break at 'it is enhanced ..." and "It is incompatible" ?

**Comment by nguillaumin** [comment]
Done:

![1](https://user-images.githubusercontent.com/762512/109416529-169c7980-79bf-11eb-8621-a48d0f8afcf1.png)

It will also apply to the text on standard releases pages, but I think it's good:

![2](https://user-images.githubusercontent.com/762512/109416537-20be7800-79bf-11eb-8249-5d1b9d895f37.png)

**Comment by nguillaumin** [comment]
I think we're happy now? So closing that one.

**Comment by stgraveyard** [comment]
Are there any examples currently in the DB?

**Comment by nguillaumin** [comment]
No, unfortunately I can't create one as there's no CPANEL available on the test site.

**Comment by stgraveyard** [comment]
Sounds like a plan. Judging from the screenshot, I like it.
