### ISSUE TITLE
Medway Boys, the VS The Medway Boys

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#86]
Nico,

![image](https://user-images.githubusercontent.com/4339294/107989487-b971f280-6fd2-11eb-8ae6-36649712f72b.png)

This team can found when clicking 'T' for The Medway Boys. This is not good imo. Shouldn't all these 'THE' teams been added differently in the DB? 

Cheers,
Maarten

**Comment by Brume-AL** [comment]
No please, don't do that!
Correct and full name is The Medway Boys (TMB).
See there:
https://demozoo.org/groups/31503/

You wouldn't name TCB "Carebears" only, or TEX "Exceptions" only, would you?

**Comment by stgraveyard** [comment]
I am not so sure. ' Medway Boys, the' is actually 'the medway boys' but better for searching...
I would make it 'Exceptions, the' and 'Carebears, the'...

**Comment by Brume-AL** [comment]
On my side I am sure ;-) Their names were The CareBears (TCB), The EXceptions (TEX), The Medway Boys (TMB), The Fallen Angels (TFA), The Bald Eagle (TBE), The Syndicate (TSC), etc. They are tons on example like that. Some case are more questionable such as The Replicants, but I never read someone writting 'this demos by "Exceptions, the" is very cool'... Everyone names them TEX or The EXceptions.

**Comment by stgraveyard** [comment]
Yeah, but Bruno, I agree with you. But in search engines and other databases, such names are presented as Carebears, the. This means their name is The Carebears, but whenbyou search ln the, you find them in the 'C' section, not the T section. Or are you saying they should be found in the T section?

**Comment by stgraveyard** [comment]
Yeah, but Bruno, I agree with you. But in search engines and other databases, such names are presented as Carebears, the. This means their name is The Carebears, but whenbyou search ln the, you find them in the 'C' section, not the T section. Or are you saying they should be found in the T section?

**Comment by Brume-AL** [comment]
Maarten which search engines or database do you refer to?

See demozoo. The Carebears aren't in the C section:

![1](https://user-images.githubusercontent.com/12120244/108030906-3e3f2980-7030-11eb-8370-3e1507156d4b.jpg)

But they are in the T section:

![2](https://user-images.githubusercontent.com/12120244/108030967-54e58080-7030-11eb-8b71-26393ac71a5f.jpg)

Same for Pouet.net. Nothing in the C section:

![3](https://user-images.githubusercontent.com/12120244/108030996-6169d900-7030-11eb-93fb-fe86fbde5ba7.jpg)

We can find them in the T section:

![4](https://user-images.githubusercontent.com/12120244/108031009-6890e700-7030-11eb-8162-f157abae6560.jpg)

**Comment by stgraveyard** [comment]
I was talking about searches in general, imdb or whatever.
Anyway, imo demozoo and pouet are displaying/searching it wrong. 
But I wil not stand in your way.
All I can say is I was looking for THE MEDWAY BOYS yesterday and did not find them, until 10 min laters I thought about looking in the T section, which doesn't make sense.
We have done the same thing for our games btw.

**Comment by nguillaumin** [comment]
Guys, I don't think there's a right or wrong answer here. Some people will see it one way, some people another way. That's why most database / websites have a "title" field, and a "title for sort" field. See for example in "Calibre" the application I use to manage my e-books:

![Screenshot from 2021-02-16 22-10-33](https://user-images.githubusercontent.com/762512/108121934-d296a400-70a3-11eb-826c-2533a9ca4cef.png)


We don't have that right now, for menus or games, which is why for games we write titles like "Adams Family, The". Personally I don't like that, I feel it looks ugly. The game should be displayed at "The Adams Family", and should also match a search for "Adams Family".

![1](https://user-images.githubusercontent.com/762512/108121801-a5e28c80-70a3-11eb-8649-8a6633182877.png)

We can achieve that with a separate sort field, but for now it's a hack.

So I think we should keep it as is for now ("The Medway Boys"), and then consider adding "title sort" fields for everything (menus, games, etc.) later.

**Comment by nguillaumin** [comment]
I'll close this for now, we'll consider a sort field in the future.
