### ISSUE TITLE
Displaying the name of the Menu on each block

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#90]
For the sake of clarity, maybe could we add the name of the menu inside each tile (just before the number of the menu)?

In that case, it could be:
- Flame Of Finland/Superior 82B
- Flame Of Finland/Superior 82C
- Flame Of Finland/Superior 83A

![Atari Legend Menu 02](https://user-images.githubusercontent.com/12120244/108199339-25f90880-711d-11eb-9316-9d79a76d522f.jpg)

**Comment by nguillaumin** [comment]
I left it out explicitly because I thought it would be too repetitive. You can only reach this page by selecting a menuset first, so presumably you know which one it is. When displaying a list of menus for a given software, the menuset name is present (with a link):

![1](https://user-images.githubusercontent.com/762512/108263934-29b17d00-7167-11eb-8722-aa9d5d9534cf.png)

That being said, I added the name now, let me know what you think.

**Comment by Brume-AL** [comment]
I agree it may look repetitive.
But when the visitor comes from a game details page (not from the main menuset page, so), I find it better to display the name of the menu.
This looks perfect to me now, thanks Nico 😉
