### ISSUE TITLE
Generate proper filenames for Downloads.

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#91]
When you download a menu - in this case it was Bad Boys #5 - the filename doesn't match. I get 112.zip.  Ergo after each download, I would have to physically rename it. This is painful.

Can I suggest a future fix for a DownloadFileName variable? It could be calculated from the menu group, plus menu number fields?

E.g. I am on the Bad Boys page and I download menu 5, the system generates the filename "BadBoys-05.zip" instead of 112.zip.

**Comment by nguillaumin** [comment]
Good point. I actually thought of that initially for the game dumps, as it also uses the database ID which is annoying. The problem is that I thought we could only do it by having PHP provide the download rather than linking to the file directly and I wanted to avoid that as it's inefficient.

I found another way though by putting a `download="filename.zip"` attribute on the link. The URL is the same, but your browser should actually use the correct name. Try it and let me know if that works for you? I will also apply it to the regular games downloads.

Should we prefix/suffix the filenames with "AtariLegend" for a bit of marketing? :stuck_out_tongue: Like `AtariLegend - Pompey Pirates 42.zip` ? @stgraveyard ?

**Comment by stgraveyard** [comment]
Hi Nico,

For me this doesn't has to be. I think @Brume-AL would be a better judge. 

Cheers.

**Comment by Brume-AL** [comment]
I don't think it's necessary to Atari Legend in the name of the file either.
The main issue with the filename is related to the menus w/o number nor letter. You can see an example here:
https://menus.atarilegend.com/menusets/71
In that case, the filename will be the same for each menu. Won't be an issue on the server, but it will for people who download files and store them on their hard drive. In that case, I used a letter on Stonish (EMP_A.ZIP, EMP_B.ZIP, etc.) since I didn't know how to solve this problem.

**Comment by nguillaumin** [comment]
Ok. I could put our internal release ID in the filename (like `Empire [no number] 1234.zip`). Not very nice as it won't mean anything to the user, but it would at least avoid duplicate names. I'd rather not add A, B, ... as it looks like if the menu itself had a letter. 

Otherwise we leave it as-is, people will just have to change the filename when saving (as their browser will ask if they want to overwrite an already existing file).

**Comment by nguillaumin** [comment]
Ah, or another idea: Put the SHA-512 short sum: `Empire [no number] (3b4e542).zip` maybe?
